name: Build and deploy MASTER branch to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Print environment
        shell: bash
        run: echo "running ${{ steps.extract_branch.outputs.branch }} build"

      - name: Checkout the repo
        uses: actions/checkout@master

      - name: Install npm packages
        shell: bash
        env:
          NODE_ENV: ${{ steps.extract_branch.outputs.branch }}
        run: |
          cd $GITHUB_WORKSPACE
          npm install

      - name: Zip the package
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          zip lambda.zip index.js

      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.0.4
        with:
          zip_file: lambda.zip
          function_name: track-map-api-handler
          publish: true
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_SECRET_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
